-- AlterTable
ALTER TABLE `User` ADD COLUMN `UserStatus` ENUM('INVITED', 'ACTIVE', 'DELETED', 'BLOCKED') NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN `role` ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER';
